name = "AbstractYieldMacros"
uuid = "71802903-5811-4e1f-b8e7-37bd234b68eb"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ContextualMacros = "18b01625-79e3-4c41-8668-c88bdfdd3c6f"

[compat]
ContextualMacros = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
